# Generated by Django 5.1.3 on 2025-04-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_competitionparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionparticipant',
            name='exercise_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='steps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
