# Generated by Django 5.1.3 on 2025-04-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_competitionparticipant_exercise_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='goal_steps',
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('steps', 'Steps'), ('minutes', 'Exercise Minutes')], default='steps', max_length=10),
            preserve_default=False,
        ),
    ]
