# Generated by Django 5.1.3 on 2025-04-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_remove_competition_goal_steps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='exercise_duration',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='exercise_type',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('steps', 'Steps'), ('exercise', 'Exercise (minutes)')], default='steps', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='steps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
