# Generated by Django 5.1.3 on 2025-04-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_remove_activitylog_exercise_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionparticipant',
            old_name='exercise_minutes',
            new_name='progress',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='competitionparticipant',
            name='steps',
        ),
    ]
