# Generated by Django 5.1.3 on 2025-04-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_rename_exercise_minutes_competitionparticipant_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='steps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
