# Generated by Django 5.1.3 on 2025-04-22 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_alter_activitylog_minutes_alter_activitylog_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='competition_type',
        ),
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
