# Generated by Django 5.1.3 on 2025-04-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_remove_activitylog_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionparticipant',
            old_name='progress',
            new_name='steps',
        ),
    ]
