# Generated by Django 5.1.3 on 2025-04-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_rename_progress_competitionparticipant_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='exercises_logged',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='steps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
