# Generated by Django 5.1.3 on 2025-04-23 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_remove_activitylog_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
